name: Static Windows binary

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        preset: [msvc-pg-static, pg-static]
    env:
      PKG_CONFIG_PATH: C:\msys64\clang64\lib\pkgconfig
      CONFIG_SITE: /etc/config.site
      MSYSTEM: CLANG64
      MINGW_PREFIX: C:\msys64\clang64
      VCPKG_ROOT: C:\vcpkg
      LDFLAGS: -Wl,--delayload=libpq.dll
    steps:
    - uses: actions/checkout@v4
    - name: Cache downloaded Pacman packages
      uses: actions/cache@v4
      with:
        path: C:\msys64\var\cache\pacman\pkg
        key: pacman-win-static
    - name: Cache the vcpkg archives
      if: matrix.preset == 'msvc-pg-static'
      uses: actions/cache@v4
      with:
        path: build/vcpkg_installed
        key: vcpkg
    - name: Add MSYS2 to PATH
      shell: pwsh
      run: |
        echo "C:\msys64\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "C:\msys64\clang64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - name: Install dependencies
      run: >-
        pacman --noconfirm -S
        mingw-w64-clang-x86_64-clang
        mingw-w64-clang-x86_64-cmake
        mingw-w64-clang-x86_64-ninja
        mingw-w64-clang-x86_64-pkgconf
        mingw-w64-clang-x86_64-postgresql
        mingw-w64-clang-x86_64-pdcurses
        mingw-w64-clang-x86_64-upx
    - name: Configure CMake
      run: cmake -B build --preset ${{ matrix.preset }} -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL=$PWD/build
    - name: Build
      run: cmake --build build --config MinSizeRel
    - name: Compress binary with UPX
      run: upx --best --ultra-brute -o build/pspg_upx.exe build/pspg.exe
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: pspg ${{ matrix.preset }} binary
        path: build/pspg*.exe
    - name: Upload CMakeCache.txt
      uses: actions/upload-artifact@v4
      if: ${{ failure() }}
      with:
        name: CMakeCache.txt
        path: build/CMakeCache.txt
