name: build Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    env:
      VCPKG_ROOT: C:\vcpkg
      # PGROOT: C:\Program Files\PostgreSQL\17

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B build --preset=msvc -DPostgreSQL_ADDITIONAL_VERSIONS=17

    - name: Build
      run: cmake --build build --config RelWithDebInfo

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Windows shlibs
        path: build/RelWithDebInfo/*
